# Generated by Django 5.2.1 on 2025-06-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, default='sample-images/no.png', null=True, upload_to='event-img/'),
        ),
    ]
