# Generated by Django 5.2.1 on 2025-06-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
