# Generated by Django 5.2.1 on 2025-06-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, default='event-img/no.png', null=True, upload_to='event-img/'),
        ),
    ]
